# [theme]
#base = "dark"
#primaryColor = "#4F8BFF"
#backgroundColor = "#0B1220"
#secondaryBackgroundColor = "#121B2E"
#textColor = "#EAF0FF"
#font = "sans serif"
[server]
headless=true
port=8501
enableCORS=false
